version: "3.8"

services:
  clerk-consumer:
    image: registry.digitalocean.com/orbizza/clerk-consumer:latest
    restart: always
    environment:
      - KAFKA_SERVICE_URI=${KAFKA_SERVICE_URI}
      - KAFKA_CA_CERT=${KAFKA_CA_CERT}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - DATABASE_URL_ONLINE=${DATABASE_URL_ONLINE}
    networks:
      - clerk-network
    volumes:
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro

  clerk-producer:
    image: registry.digitalocean.com/orbizza/clerk-producer:latest
    restart: always
    expose:
      - "3010"
    environment:
      - PORT=3010
      - CLERK_WEBHOOK_SECRET=${CLERK_WEBHOOK_SECRET}
      - KAFKA_SERVICE_URI=${KAFKA_SERVICE_URI}
      - KAFKA_CA_CERT=${KAFKA_CA_CERT}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
    networks:
      - clerk-network
    volumes:
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - clerk-producer
    networks:
      - clerk-network
    restart: always

networks:
  clerk-network:
    driver: bridge
