version: "3.8"

services:
  review-algolia-update:
    image: registry.digitalocean.com/orbizza/review-algolia-update:latest
    restart: always
    environment:
      - KAFKA_SERVICE_URI=${KAFKA_SERVICE_URI}
      - KAFKA_CA_CERT=${KAFKA_CA_CERT}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - ALGOLIA_APP_ID=${ALGOLIA_APP_ID}
      - ALGOLIA_ADMIN_API_KEY=${ALGOLIA_WRITE_API_KEY}
    networks:
      - review-network
    volumes:
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro

  review-calculate:
    image: registry.digitalocean.com/orbizza/review-calculate:latest
    restart: always
    environment:
      - KAFKA_SERVICE_URI=${KAFKA_SERVICE_URI}
      - KAFKA_CA_CERT=${KAFKA_CA_CERT}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - DATABASE_URL_ONLINE=${DATABASE_URL_ONLINE}
    networks:
      - review-network
    volumes:
      - ${HOME}/.docker/config.json:/root/.docker/config.json:ro

networks:
  review-network:
    driver: bridge
