import React from "react";

import { IconCloud } from "@ratecreator/ui";

const slugs = [
  // Popular Social Media Platforms with messaging apps
  "facebook",
  "twitter",
  "instagram",
  "linkedin",
  "youtube",
  "snapchat",
  "tiktok", // Although owned by ByteDance, it's globally focused
  "whatsapp",
  "pinterest",
  "reddit",
  "tumblr",
  "telegram",
  "medium",
  "slack",
  "discord",
  "dribbble",
  "behance",
  "flickr",
  "twitch",
  "messenger",
  "vimeo",
  "clubhouse",
  "quora",
  "xing",
  "mix",
  "mastodon",
  "mewe",
  "vk",
  "signal",
  "gab",
  "parler",
  "viber",
  "meetup",
];

// const slugs = [
//   // Popular Social Media Platforms with messaging apps
//   "facebook",
//   "twitter",
//   "instagram",
//   "linkedin",
//   "youtube",
//   "snapchat",
//   "tiktok",
//   "whatsapp",
//   "pinterest",
//   "reddit",
//   "tumblr",
//   "telegram",
//   "medium",
//   "slack",
//   "discord",
//   "dribbble",
//   "behance",
//   "flickr",
//   "twitch",
//   "wechat",
//   "messenger",
//   "vimeo",
//   "clubhouse",
//   "quora",
//   "xing",
//   "mix",
//   "mastodon",
//   "mewe",
//   "vk",
//   "line",
//   "qq",
//   "renren",
//   "douyin",
//   "signal",
//   "gab",
//   "parler",
//   "viber",
//   "weibo",
//   "meetup",
// ];

// const slugs = [
//   // Popular Social Media Platforms
//   "facebook",
//   "twitter",
//   "instagram",
//   "linkedin",
//   "youtube",
//   "snapchat",
//   "tiktok",
//   "pinterest",
//   "reddit",
//   "tumblr",
//   "medium",
//   "slack",
//   "discord",
//   "dribbble",
//   "behance",
//   "flickr",
//   "twitch",
//   "vimeo",
//   "clubhouse",
//   "quora",
//   "xing",
//   "mix",
//   "mastodon",
//   "mewe",
//   "vk",
//   "renren",
//   "douyin",
//   "gab",
//   "parler",
//   "weibo",
//   "meetup",
// ];

export function IconCloudSection() {
  return (
    <div className="bg-background relative flex size-full max-w-lg items-center justify-center overflow-hidden rounded-lg  px-20 pb-20 pt-8 ">
      <IconCloud iconSlugs={slugs} />
    </div>
  );
}
